# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  port: 3306
  timeout: 5000
  socket: /tmp/mysql.sock
  username: root
  host: localhost

development:
  <<: *default
  database: six_on_cloud_development

test:
  <<: *default
  database: six_on_cloud_test
